stages:
  - build
  - deploy

# ==================== BUILD (только сборка) ====================
build:
  stage: build
  image: docker:24-cli
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  script:
    - apk add --no-cache docker-compose
    - |
      docker build \
        --no-cache \
        --pull \
        --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN \
        --add-host=gitlab.local:host-gateway \
        -t biometric-demo:latest .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

# ==================== DEPLOY ====================
deploy:
  stage: deploy
  image: docker:24-cli
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  script:
    - apk add --no-cache docker-compose

    # Полная чистая пересборка (гарантирует свежий app.py)
    - |
      docker build \
        --no-cache \
        --pull \
        --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN \
        --add-host=gitlab.local:host-gateway \
        -t biometric-demo:latest .

    # Очистка старого
    - docker compose down --remove-orphans || true
    - docker builder prune -f --all || true
    - docker system prune -f --all || true

    # Запуск (исправленный флаг)
    - docker compose up -d --force-recreate --pull always

  rules:
    - if: $CI_PIPELINE_SOURCE == "push"