version: '3.8'

services:
  biometric-demo:
    build:
      context: .
      extra_hosts:
        - "gitlab.local:host-gateway"
    ports:
      - "8501:8501"
    restart: unless-stopped

    # Для разработки (можно раскомментировать):
    # volumes:
    #   - .:/app